--------------------------------------------------------
--  DDL for Table FACT_ORDER_LINE
--------------------------------------------------------

drop table FACT_ORDER_LINE_P purge;

  CREATE TABLE "GCBC_PEF"."FACT_ORDER_LINE_P" 
   (	"SALES_ORDER_LINE_ID" NUMBER, 
	"SALES_ORDER_ID" NUMBER, 
	"PRODUCT_KEY" NUMBER, 
	"CUSTOMER_KEY" NUMBER, 
	"CUSTOMER_ADDRESS_KEY" NUMBER, 
	"STAFF_KEY" NUMBER, 
	"STAFF_ADDRESS_KEY" NUMBER, 
	"SALE_ORDER_TIME_KEY" NUMBER, 
	"ORDER_DATE_NUMBER" NUMBER, 
	"OUTLET_KEY" NUMBER, 
	"OUTLET_ADDRESS_KEY" NUMBER, 
	"CURRENCY_KEY" NUMBER, 
	"QUANTITY" NUMBER, 
	"DISCOUNT" NUMBER(5,2), 
	"UNIT_PRICE" NUMBER, 
	"UNIT_COST" NUMBER, 
	"ATTRIBUTE_SALE_PRICE" NUMBER, 
	"ATTRIBUTE_COST" NUMBER, 
	"INTERNET_ORDER_FLAG" VARCHAR2(1 BYTE), 
	"LOYALTY_CARD_FLAG" VARCHAR2(1 BYTE), 
	"SALE_ORDER_DATE_KEY" NUMBER(8,0), 
	"REVENUE" NUMBER(18,2), 
	"COST" NUMBER(18,2), 
	"REVENUE_USD" NUMBER(18,2), 
	"REVENUE_GBP" NUMBER(18,2), 
	"COST_USD" NUMBER(18,2), 
	"COST_GBP" NUMBER(18,2), 
	"SALE_ORDER_DATE" DATE
   ) pctfree 0 compress
   partition by range (sale_order_date)
   INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
   (
     PARTITION P0 values less than (TO_DATE('1-7-2009', 'DD-MM-YYYY')) pctfree 0 compress
   );
--------------------------------------------------------
--  DDL for Index IND_SALES_ORDER_LINE_ID
--------------------------------------------------------

--  CREATE UNIQUE INDEX "GCBC_PEF"."IND_SALES_ORDER_LINE_ID" ON "GCBC_PEF"."FACT_ORDER_LINE" ("SALES_ORDER_LINE_ID") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT_ORDER_LINE
--------------------------------------------------------

  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("SALES_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("PRODUCT_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("CUSTOMER_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("STAFF_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("STAFF_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("SALE_ORDER_TIME_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("OUTLET_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("OUTLET_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" MODIFY ("CURRENCY_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FACT_ORDER_LINE
--------------------------------------------------------

  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_CUSTOMER_ADDR_FK" FOREIGN KEY ("CUSTOMER_ADDRESS_KEY")
	  REFERENCES "GCBC_PEF"."DIM_ADDRESS" ("ADDRESS_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_CURRENCY_FK" FOREIGN KEY ("CURRENCY_KEY")
	  REFERENCES "GCBC_PEF"."DIM_CURRENCY" ("CURRENCY_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_CUSTOMERS_FK" FOREIGN KEY ("CUSTOMER_KEY")
	  REFERENCES "GCBC_PEF"."DIM_CUSTOMERS" ("CUSTOMER_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_DATE_FK" FOREIGN KEY ("SALE_ORDER_DATE_KEY")
	  REFERENCES "GCBC_PEF"."DIM_DATE" ("DIM_DATE_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_OUTLET_FK" FOREIGN KEY ("OUTLET_KEY")
	  REFERENCES "GCBC_PEF"."DIM_OUTLETS" ("OUTLET_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_PRODUCTS_FK" FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "GCBC_PEF"."DIM_PRODUCTS" ("PRODUCT_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_DIM_STAFF_FK" FOREIGN KEY ("STAFF_KEY")
	  REFERENCES "GCBC_PEF"."DIM_STAFF" ("STAFF_KEY") DISABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE" ADD CONSTRAINT "F_ORDER_LINE_OUTLET_ADDR_FK" FOREIGN KEY ("OUTLET_ADDRESS_KEY")
	  REFERENCES "GCBC_PEF"."DIM_ADDRESS" ("ADDRESS_KEY") DISABLE;
