--------------------------------------------------------
--  DDL for Table FACT_ORDER_LINE_ATT
--------------------------------------------------------

  CREATE TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT_P" 
   (	"PRODUCT_KEY" NUMBER, 
	"CUSTOMER_KEY" NUMBER, 
	"CUSTOMER_ADDRESS_KEY" NUMBER, 
	"STAFF_KEY" NUMBER, 
	"STAFF_ADDRESS_KEY" NUMBER, 
	"TIME_KEY" NUMBER, 
	"OUTLET_KEY" NUMBER, 
	"OUTLET_ADDRESS_KEY" NUMBER, 
	"ATTRIBUTE_KEY" NUMBER, 
	"SALES_ORDER_ID" NUMBER, 
	"SALES_ORDER_LINE_ID" NUMBER, 
	"ATTRIBUTE_PRICE" NUMBER, 
	"ATTRIBUTE_COST" NUMBER(5,3), 
	"ORDER_DATE_KEY" NUMBER(10,0), 
	"INTERNET_ORDER_FLAG" VARCHAR2(1 BYTE), 
	"LOYALTY_CARD_FLAG" VARCHAR2(1 BYTE), 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 
 COMPRESS NOLOGGING
   partition by range (order_date)
   INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
   (
     PARTITION P0 values less than (TO_DATE('1-7-2009', 'DD-MM-YYYY')) pctfree 0 compress
   );
--------------------------------------------------------
--  Constraints for Table FACT_ORDER_LINE_ATT
--------------------------------------------------------

  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("PRODUCT_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("CUSTOMER_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("CUSTOMER_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("STAFF_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("STAFF_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("TIME_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("OUTLET_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("OUTLET_ADDRESS_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("ATTRIBUTE_KEY" NOT NULL ENABLE);
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" MODIFY ("SALES_ORDER_LINE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FACT_ORDER_LINE_ATT
--------------------------------------------------------

  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_CUST_ADDR_FK" FOREIGN KEY ("CUSTOMER_ADDRESS_KEY")
	  REFERENCES "GCBC_PEF"."DIM_ADDRESS" ("ADDRESS_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_ATTRIB_FK" FOREIGN KEY ("ATTRIBUTE_KEY")
	  REFERENCES "GCBC_PEF"."DIM_ATTRIBUTES" ("ATTRIBUTE_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_KEY")
	  REFERENCES "GCBC_PEF"."DIM_CUSTOMERS" ("CUSTOMER_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_DATE_FK" FOREIGN KEY ("ORDER_DATE_KEY")
	  REFERENCES "GCBC_PEF"."DIM_DATE" ("DIM_DATE_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_OUTLET_FK" FOREIGN KEY ("OUTLET_KEY")
	  REFERENCES "GCBC_PEF"."DIM_OUTLETS" ("OUTLET_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_PRODUCT_FK" FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "GCBC_PEF"."DIM_PRODUCTS" ("PRODUCT_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_DIM_STAFF_FK" FOREIGN KEY ("STAFF_KEY")
	  REFERENCES "GCBC_PEF"."DIM_STAFF" ("STAFF_KEY") ENABLE;
  ALTER TABLE "GCBC_PEF"."FACT_ORDER_LINE_ATT" ADD CONSTRAINT "FACT_ORDER_ATT_OUTLET_ADDR_FK" FOREIGN KEY ("OUTLET_ADDRESS_KEY")
	  REFERENCES "GCBC_PEF"."DIM_ADDRESS" ("ADDRESS_KEY") ENABLE;
